### ISSUE TITLE
package.json is not correct...

### ISSUE THREAD

**Issue by spants** [aklambeth/node-red-contrib-hive#1]
Need to change nodes to include options:

"node-red": {
    "nodes": {
      "hive": "hive.js",
      "Heating": "HeatingController.js",
      "HotWater": "HotWaterController.js",
      "Temperature": "Temperature.js"
    }
  },

**Comment by aklambeth** [comment]
Fixed in the pre-release version. Package now also uses current implementation of bg-hive-api which fixes breaking changes in the api.
